CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(200) NOT NULL,
                          slug VARCHAR(200) NOT NULL UNIQUE,
                          description TEXT NOT NULL,
                          price NUMERIC(12, 2) NOT NULL CHECK (price >= 0),
                          image_url VARCHAR(500) NOT NULL,
                          active BOOLEAN NOT NULL DEFAULT TRUE,
                          category_id BIGINT NOT NULL,
                          created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT fk_products_category
                              FOREIGN KEY (category_id)
                                  REFERENCES categories (id)
);

CREATE INDEX idx_products_category_id ON products (category_id);