spring.application.name=cartcraft-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/cartcraft}
spring.datasource.username=${DB_USERNAME:cartcraft}
spring.datasource.password=${DB_PASSWORD:cartcraft-local}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false